' Launches ObsidianPushOnExit.ps1 with no visible window (generated by installer/setup.ps1).
' Point your shortcut to this .vbs (same folder as the .ps1).
' Uses 64-bit PowerShell when possible (32-bit WScript maps System32 to SysWOW64).

Const VAULT_PATH = __VAULT_PATH__

Function GetPowerShellExe(fso)
    Dim sh, root, p
    Set sh = CreateObject("WScript.Shell")
    root = sh.ExpandEnvironmentStrings("%SystemRoot%")
    p = root & "\Sysnative\WindowsPowerShell\v1.0\powershell.exe"
    If fso.FileExists(p) Then
        GetPowerShellExe = p
        Exit Function
    End If
    p = root & "\System32\WindowsPowerShell\v1.0\powershell.exe"
    If fso.FileExists(p) Then
        GetPowerShellExe = p
        Exit Function
    End If
    GetPowerShellExe = "powershell.exe"
End Function

Dim shell, fso, ps1, cmd, pwsh
Set fso = CreateObject("Scripting.FileSystemObject")
ps1 = fso.BuildPath(fso.GetParentFolderName(WScript.ScriptFullName), "ObsidianPushOnExit.ps1")

If Not fso.FileExists(ps1) Then
    MsgBox "Not found: " & ps1, vbCritical, "ObsidianPushOnExit-Hidden"
    WScript.Quit 1
End If

pwsh = GetPowerShellExe(fso)
cmd = """" & pwsh & """ -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & ps1 & """ -VaultPath """ & VAULT_PATH & """"

Dim logDir, logFile, ts
logDir = fso.BuildPath(fso.GetParentFolderName(WScript.ScriptFullName), "logs")
logFile = fso.BuildPath(logDir, "launcher.log")
On Error Resume Next
If Not fso.FolderExists(logDir) Then fso.CreateFolder logDir
If Err.Number <> 0 Then Err.Clear
Set ts = fso.OpenTextFile(logFile, 8, True)
If Err.Number = 0 Then
    ts.WriteLine Now & " ObsidianPushOnExit-Hidden.vbs -> " & cmd
    ts.Close
End If
On Error GoTo 0

Set shell = CreateObject("WScript.Shell")
shell.Run cmd, 0, False
